package com.isfandroid.pomodaily.utils

object Constant {
    // DATA - LOCAL - PREFS
    const val APP_PREFS = "APP_PREFS"
    const val PREFS_KEY_IS_ON_BOARDING_DONE = "PREFS_KEY_IS_ON_BOARDING_DONE"

    // NAVIGATION
    const val NAV_DESTINATION_ON_BOARDING = "NAV_DESTINATION_ON_BOARDING"
    const val NAV_DESTINATION_SCHEDULE = "NAV_DESTINATION_SCHEDULE"
    const val NAV_DESTINATION_CREATE_DAILY_TASKS = "NAV_DESTINATION_CREATE_DAILY_TASKS"
    const val NAV_DESTINATION_POMODORO = "NAV_DESTINATION_POMODORO"
}