package com.isfandroid.pomodaily.utils

object Constant {
    // DATA - LOCAL - PREFS
    const val APP_PREFS = "APP_PREFS"
    const val PREFS_KEY_IS_ON_BOARDING_DONE = "PREFS_KEY_IS_ON_BOARDING_DONE"
    const val PREFS_KEY_POMODORO_COUNT = "PREFS_KEY_POMODORO_COUNT"
    const val PREFS_KEY_POMODORO_DURATION = "PREFS_KEY_POMODORO_DURATION"
    const val PREFS_KEY_BREAK_DURATION = "PREFS_KEY_BREAK_DURATION"
    const val PREFS_KEY_LONG_BREAK_DURATION = "PREFS_KEY_LONG_BREAK_DURATION"
    const val PREFS_KEY_LONG_BREAK_INTERVAL = "PREFS_KEY_LONG_BREAK_INTERVAL"
    const val PREFS_KEY_SETTINGS_AUTO_START_BREAKS = "PREFS_KEY_SETTINGS_AUTO_START_BREAKS"
    const val PREFS_KEY_SETTINGS_AUTO_START_POMODOROS = "PREFS_KEY_SETTINGS_AUTO_START_POMODOROS"
    const val PREFS_KEY_LAST_RESET_DATE = "PREFS_KEY_LAST_RESET_DATE"
    const val PREFS_KEY_ACTIVE_TASK_ID = "PREFS_KEY_ACTIVE_TASK_ID"

    // DATA - LOCAL - PREFS - VALUES
    const val DEFAULT_POMODORO_MINUTES = 25
    const val DEFAULT_BREAK_MINUTES = 5
    const val DEFAULT_LONG_BREAK_MINUTES = 10
    const val DEFAULT_LONG_BREAK_INTERVAL = 4
    const val DEFAULT_POMODORO_COUNT = 0
    const val DEFAULT_AUTO_START_POMODOROS = true
    const val DEFAULT_AUTO_START_BREAKS = true

    // DATA - LOCAL - DATABASE
    const val DB_NAME = "pomodaily.db"

    // NAVIGATION
    const val NAV_DESTINATION_ON_BOARDING = "NAV_DESTINATION_ON_BOARDING"
    const val NAV_DESTINATION_POMODORO = "NAV_DESTINATION_POMODORO"

    // TIMER STATE
    const val TIMER_STATE_IDLE = "TIMER_STATE_IDLE"
    const val TIMER_STATE_RUNNING = "TIMER_STATE_RUNNING"
    const val TIMER_STATE_PAUSED = "TIMER_STATE_PAUSED"

    // TIMER TYPE
    const val TIMER_TYPE_POMODORO = "TIMER_TYPE_POMODORO"
    const val TIMER_TYPE_BREAK = "TIMER_TYPE_BREAK"
    const val TIMER_TYPE_LONG_BREAK = "TIMER_TYPE_LONG_BREAK"

    // OTHERS
    const val STATE_IN_TIMEOUT_MS = 5000L

    // WORKER
    const val DAILY_RESET_WORK = "DAILY_RESET_WORK"

    // NOTIFICATIONS - TIMER
    const val POMODORO_TIMER_NOTIFICATION_ID = 101
    const val POMODORO_TIMER_CHANNEL_ID = "CHANNEL_TIMER"
    const val POMODORO_TIMER_CHANNEL_NAME = "POMODAILY_POMODORO_TIMER_CHANNEL"


    // NOTIFICATIONS - ALERT
    const val POMODORO_ALERT_NOTIFICATION_ID = 102
    const val POMODORO_ALERT_CHANNEL_ID = "CHANNEL_ALERT"
    const val POMODORO_ALERT_CHANNEL_NAME = "POMODAILY_POMODORO_ALERT_CHANNEL"
}